spring:
    application:
        name: SMC-Eureka-Server
    profiles:  
        active: dev
server:
    port: 8761
---
spring:
    profiles: dev

eureka:
    instance: 
        hostname: localhost
    client:
        service-url: 
            defaultZone: http://localhost:8761/eureka/
        register-with-eureka: false
        fetch-registry: false

---
spring:
    profiles: prod

eureka:
    client:
        service-url:     
            defaultZone: http://101.201.102.101:8761/eureka
